### ISSUE TITLE
Where do I learn the implementation of these patterns?

### ISSUE THREAD

**Issue by marcofugaro** [fbeline/design-patterns-JS#13]
I wanted to learn these pattern, but not coming from anther language where those pattern are more common, it's really hard for me knowing when and how to use those with really basic examples.

Do you know of any more "real-world" examples of the patterns?

**Comment by zapkub** [comment]
this is a really good question. I hope there are some senario describe in code comment.

**Comment by BlackbeardMatt** [comment]
I always recommend Head First Design Patterns (it's used as a textbook in many CS and SE curriculums and is exclusively Java in the book) or if you can't find or are unable to purchase the book, I recommend: https://sourcemaking.com/design_patterns

Each of the patterns on their site has a bunch of example code in different languages.

**Comment by Badacadabra** [comment]
@marcofugaro I think I have exactly what you are looking for because I worked on this topic last year. I covered most design patterns (including GoF ones), in two flavors (classic & idiomatic). I also implemented all of them in **ES5, ES6, CoffeeScript and TypeScript**. For each design pattern, you get a **real-world example with a synopsis, a problem and a solution with a UML diagram**. If you think it might be useful to you, please take a look at my repo: [**PatternifyJS**](https://github.com/Badacadabra/PatternifyJS).

(*Given the popularity of Felipe's repo, I am wondering if it was not a terrible mistake to choose such an obscure name for my own repo. I will probably change it to make it more explicit...*)
